server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModuleProperty
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: consumerModuleProperty
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**